# https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

version: 2

sphinx:
  builder: html

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  apt_packages:
    - curl
    - build-essential
    - gcc
    - make
  jobs:
    pre_create_environment:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
