[project]
name = "ncollpyde"
description = "Point/line-mesh intersection queries in python"
readme = "README.rst"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [{ name = "Chris L. Barnes", email = "chrislloydbarnes@gmail.com" }]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Programming Language :: Rust",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dynamic = ["version"]

dependencies = ["numpy>=1.21.0"]

[project.optional-dependencies]
validate = ["trimesh[easy]>=3.7.7"]

[dependency-groups]
test = ["meshio==5.3.5", "pytest==7.2.2", "pytest-runner==6.0.0"]
bench = ["pytest-benchmark==4.0.0"]
dev = [
  "pip",
  "ruff",
  "mypy",
  { include-group = "test" },
  { include-group = "bench" },
]

[project.urls]
homepage = "https://pypi.org/project/ncollpyde/"
documentation = "https://ncollpyde.readthedocs.io/"
repository = "https://github.com/clbarnes/ncollpyde/"

[build-system]
requires = ["maturin==1.9.6", "numpy>=1.21"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
module-name = "ncollpyde._ncollpyde"

[tool.mypy]
ignore_missing_imports = true
plugins = ["numpy.typing.mypy_plugin"]
python_version = "3.12"

[tool.ruff]
extend-exclude = ["docs"]
target-version = "py310"
