[project]
name = "ncollpyde"
description = "Point/line-mesh intersection queries in python"
readme = "README.rst"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [
  {name = "Chris L. Barnes", email = "chrislloydbarnes@gmail.com"},
]
dynamic = ["version"]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Programming Language :: Rust",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14"
]

dependencies = [
    "numpy>=2.0",
]

[project.optional-dependencies]
validate = ["trimesh[easy]>=4.0"]
# should be specified as dependency-groups,
# but maturin doesn't support them yet
# https://github.com/PyO3/maturin/issues/2737
dev = [
    # lints
    "ruff",
    "mypy",
    # test dependencies
    "meshio",
    "pytest",
    "pytest-benchmark",
]

[project.urls]
homepage = "https://pypi.org/project/ncollpyde/"
documentation = "https://ncollpyde.readthedocs.io/"
repository = "https://github.com/clbarnes/ncollpyde/"

[build-system]
requires = ["maturin==1.14.1", "numpy>=2"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
module-name = "ncollpyde._ncollpyde"

[tool.mypy]
ignore_missing_imports = true
plugins = ["numpy.typing.mypy_plugin"]
python_version = "3.10"

[tool.ruff]
extend-exclude = ["docs"]
target-version = "py310"
