[project]
name = "ncollpyde"
description = "Point/line-mesh intersection queries in python"
readme = "README.rst"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [
  {name = "Chris L. Barnes", email = "chrislloydbarnes@gmail.com"},
]
dynamic = ["version"]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Programming Language :: Rust",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14"
]

dependencies = [
    "numpy>=2.0",
]

[project.optional-dependencies]
validate = ["trimesh[easy]>=4.0"]
# should be specified as dependency-groups,
# but maturin doesn't support them yet
# https://github.com/PyO3/maturin/issues/2737

[dependency-groups]
lint = ["ruff", "mypy"]
test = ["meshio", "pytest", "pytest-benchmark"]
doc = ["Sphinx==6.1.3", "sphinx-rtd-theme"]
dev = [
    "maturin==1.14.1",
    "maturin-import-hook",
    {include-group = "lint"},
    {include-group = "test"},
    {include-group = "doc"},
]

[project.urls]
homepage = "https://pypi.org/project/ncollpyde/"
documentation = "https://ncollpyde.readthedocs.io/"
repository = "https://github.com/clbarnes/ncollpyde/"

[build-system]
requires = ["maturin==1.14.1", "numpy>=2"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
module-name = "ncollpyde._ncollpyde"

[tool.mypy]
ignore_missing_imports = true
plugins = ["numpy.typing.mypy_plugin"]
python_version = "3.10"

[tool.ruff]
extend-exclude = ["docs"]
target-version = "py310"

[tool.uv]
package = false

# This would allow uv to rebuild the rust package as part of `uv sync`,
# but does so in --release mode (not good for dev/ CI)
# cache-keys = [{file = "pyproject.toml"}, {file = "Cargo.toml"}, {file = "**/*.rs"}]

# This would allow uv to rebuild the rust package in --dev mode,
# but would probably use --dev when doing `uv publish` too.
# config-settings = { build-args = "--profile=dev" }
