on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  lint-rust:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: make lint-rust

  lint-python:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v9.0.0
      - run: make sync
      - run: make lint-python

  test-rust:
    strategy:
      fail-fast: false
      matrix:
        rust-version: [stable, beta, nightly]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-version }}
      - uses: astral-sh/setup-uv@v9.0.0
      - uses: Swatinem/rust-cache@v2
      - run: cargo test

  test-python:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: sudo apt-get install libspatialindex-dev
        name: Install OS dependencies
      - run: |
          mkdir -p $TGT_DIR
          rm -f $TGT_DIR/*.whl
          make sync
          uv run maturin build --release --interpreter python --out $TGT_DIR
          uv pip install $TGT_DIR/*.whl
        name: Install package
        env:
          TGT_DIR: "target/wheels/${{ matrix.python-version }}"
      - run: pytest --verbose

  deploy:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-24.04]
    needs: [lint-rust, lint-python, test-rust, test-python]
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: astral-sh/setup-uv@v9.0.0
      - uses: PyO3/maturin-action@v1
        with:
          manylinux: auto
          command: publish
          args: -u __token__ -p ${{ secrets.MATURIN_PASSWORD }} --skip-existing --universal2
        name: Deploy wheels
